version: "3.8"
services:
  web:
    build:
      context: ./
    environment:
      - FLASK_APP=app.py
    ports:
      - "5432:5432"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_USER=ml_service
      - POSTGRES_PASSWORD=ml_pass
      - POSTGRES_DB=ml_service_db
    ports:
      - "5000:5000"

