version: "3.8"
services:
  web:
    build:
      context: ./
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ml_service
      - POSTGRES_PASSWORD=ml_pass
      - POSTGRES_DB=ml_service_db
volumes:
  postgres_data:
