# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_message_header.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kafka_message_header.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n*com.wine.to.up.catalog.service.api.message',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1akafka_message_header.proto\"0\n\x12KafkaMessageHeader\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x42,\n*com.wine.to.up.catalog.service.api.messageb\x06proto3'
)




_KAFKAMESSAGEHEADER = _descriptor.Descriptor(
  name='KafkaMessageHeader',
  full_name='KafkaMessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KafkaMessageHeader.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='KafkaMessageHeader.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['KafkaMessageHeader'] = _KAFKAMESSAGEHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KafkaMessageHeader = _reflection.GeneratedProtocolMessageType('KafkaMessageHeader', (_message.Message,), {
  'DESCRIPTOR' : _KAFKAMESSAGEHEADER,
  '__module__' : 'kafka_message_header_pb2'
  # @@protoc_insertion_point(class_scope:KafkaMessageHeader)
  })
_sym_db.RegisterMessage(KafkaMessageHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
