# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_wine_saved_message_sent_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from kafka_listener.schema import kafka_message_header_pb2 as kafka__message__header__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='new_wine_saved_message_sent_event.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n*com.wine.to.up.catalog.service.api.message',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'new_wine_saved_message_sent_event.proto\x1a\x1akafka_message_header.proto\"f\n\x1cNewWineSavedMessageSentEvent\x12\x0e\n\x06wineId\x18\x01 \x01(\t\x12\x10\n\x08wineName\x18\x02 \x01(\t\x12$\n\x07headers\x18\x03 \x03(\x0b\x32\x13.KafkaMessageHeaderB,\n*com.wine.to.up.catalog.service.api.messageb\x06proto3'
  ,
  dependencies=[kafka__message__header__pb2.DESCRIPTOR,])




_NEWWINESAVEDMESSAGESENTEVENT = _descriptor.Descriptor(
  name='NewWineSavedMessageSentEvent',
  full_name='NewWineSavedMessageSentEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wineId', full_name='NewWineSavedMessageSentEvent.wineId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wineName', full_name='NewWineSavedMessageSentEvent.wineName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='NewWineSavedMessageSentEvent.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=173,
)

_NEWWINESAVEDMESSAGESENTEVENT.fields_by_name['headers'].message_type = kafka__message__header__pb2._KAFKAMESSAGEHEADER
DESCRIPTOR.message_types_by_name['NewWineSavedMessageSentEvent'] = _NEWWINESAVEDMESSAGESENTEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewWineSavedMessageSentEvent = _reflection.GeneratedProtocolMessageType('NewWineSavedMessageSentEvent', (_message.Message,), {
  'DESCRIPTOR' : _NEWWINESAVEDMESSAGESENTEVENT,
  '__module__' : 'new_wine_saved_message_sent_event_pb2'
  # @@protoc_insertion_point(class_scope:NewWineSavedMessageSentEvent)
  })
_sym_db.RegisterMessage(NewWineSavedMessageSentEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
