summary: "Get recommendations"
description: "Wine recommendation by description"
dom_id: "#swagger-ui"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - "ml-description-based-recommendation-service"
parameters:
  - in: query
    name: "id"
    description: "wine position id in catalog database"
    required: true
    schema:
      type: string
  - in: query
    name: "k"
    description: "desired number of recommendations, default 10"
    required: false
    schema:
      type: integer
  - in: query
    name: "description"
    description: "full wine description, containing 'aroma' + 'taste' + 'description' fields"
    required: false
    schema:
      type: string
responses:
  200:
    description: "Successful recommendation"
  503:
    description: "Internal server error"


