summary: "Retrain model"
description: "Full model retraining. Very long process, not required for recommendations"
dom_id: "#swagger-ui"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - "ml-description-based-recommendation-service"
responses:
  200:
    description: "Model successfully retrained"
  503:
    description: "Internal server error"


